#You have to configure your repository - Settings -> Action -> General -> Workflow permissions and choose read and write permissions

name: test flow

on:
  workflow_dispatch

jobs:
  rundascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: |
          chmod +x update-add.sh
          ./update-add.sh
          python my_file.py
          python ip.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "crongenerated"
          git push
